version: '3'
services:
  database:
    image: postgres:alpine
    ports:
      - "5436:5432"
    networks:
      - backend
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  application:
    build:
      context: .
    ports:
      - "8081:8080"
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - backend
volumes:
  postgres:
networks:
  backend: